# Generated by Django 5.2.12 on 2026-03-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('VA', 'Vertical (Apartamento)'), ('LO', 'Loteamento / Cond. Fechado')], max_length=2)),
                ('construtora', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.TextField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('unidades_totais', models.IntegerField(default=0)),
                ('unidades_vendidas', models.IntegerField(default=0)),
                ('estoque', models.IntegerField(default=0)),
                ('percentual_vendido', models.FloatField(default=0.0)),
                ('preco_medio_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_unidade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('area_unidade', models.FloatField(null=True)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('vagas_garagem', models.CharField(blank=True, max_length=100, null=True)),
                ('fase_obra', models.CharField(blank=True, max_length=100, null=True)),
                ('lazer', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
