# Generated by Django 5.2.12 on 2026-03-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='data_comercializacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
