# Generated by Django 5.2.12 on 2026-03-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empreendimento_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='categoria',
            field=models.CharField(choices=[('VA', 'Vertical (Apartamento)'), ('LO', 'Loteamento / Cond. Fechado')], max_length=20),
        ),
    ]
