# Generated by Django 5.2.12 on 2026-03-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empreendimento_data_comercializacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='abas_ativas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de slugs das abas habilitadas. Vazio = todas.'),
        ),
    ]
