# Generated by Django 5.2.12 on 2026-03-23 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dashboard_abas_ativas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='abas_ativas',
            field=models.TextField(default='["mapa", "tabela", "graficos", "pricing"]'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
