# Generated by Django 5.2.12 on 2026-03-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dashboard_abas_ativas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='abas_ativas',
            field=models.TextField(default='["mapa", "tabela", "graficos", "pricing", "estoque", "mapa_calor", "comparativo", "evolucao", "analise_preco"]'),
        ),
    ]
