# Generated by Django 5.2.12 on 2026-03-30 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_dashboard_abas_ativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='ref_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='ref_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='ref_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('logistico', 'Logístico')], default='residencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='abas_ativas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmpreendimentoLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('construtora', models.CharField(blank=True, max_length=255, null=True)),
                ('proprietario', models.CharField(blank=True, max_length=500, null=True)),
                ('fase_obra', models.CharField(blank=True, max_length=100, null=True)),
                ('num_galpoes', models.IntegerField(blank=True, null=True)),
                ('num_modulos', models.IntegerField(blank=True, null=True)),
                ('modulos_ocupados', models.IntegerField(blank=True, null=True)),
                ('modulos_disponiveis', models.IntegerField(blank=True, null=True)),
                ('preco_m2_locacao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_m2_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_m2_iptu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preco_locacao', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preco_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preco_iptu', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('area_modulo_m2', models.FloatField(blank=True, null=True)),
                ('abl_m2', models.FloatField(blank=True, null=True)),
                ('vacancia', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distancia_ref_km', models.FloatField(blank=True, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('dashboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empreendimentos_logisticos', to='app.dashboard')),
                ('empreendimento_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipologias', to='app.empreendimentologistico')),
            ],
            options={
                'ordering': ['numero', 'nome'],
            },
        ),
    ]
